import java.util.Random;
import java.util.Scanner;
public class TwoD_ARRAY {
    public static void main(String[] args) throws Exception {
    Scanner sc = new Scanner (System.in);
    
    //Create a 2D array of integers and allow the user to input the dimensions
    //Then, fill the array with numbers inputted by the user.(number of rows and columns). 
  
    // System.out.println("Enter size of the array: ");
    // System.out.print("Enter rows: ");
    // int rows = sc.nextInt();
        
    // System.out.print("Enter columns: ");
    // int columns = sc.nextInt();

    // int array [][] = new int[rows][columns];

    // System.out.println("Enter" + " " + (rows * columns) + " " + "element: ");
    // for (int i = 0; i < rows; i++) {
    //     for (int j = 0; j < columns; j++) {
    //         array[i][j] = sc.nextInt();
    //     }    
    // }
    // sc.close();

    // System.out.println("The array is : ");
    // for (int i = 0; i < rows; i++) {
    //     for (int j = 0; j < columns; j++) {
    //         System.out.print(array [i][j] + " ");
    //     }
    //     System.out.println();
    // }
    
    
   

// -----------S A M E ^------------------------------------------------------------------------------
// for back up

    // System.out.print("Enter the number of rows: ");
    // int rows1 = sc.nextInt();

    // System.out.print("Enter the number of columns: ");
    // int columns1 = sc.nextInt();

    // int[][] array1 = new int[rows1][columns1];

    // System.out.println("Enter the elements of the array:");
    // for (int i = 0; i < rows1; i++) {
    //     for (int j = 0; j < columns1; j++) {
    //         array1[i][j] = sc.nextInt();
    //     }
    // }

    // sc.close();

    // System.out.println("The 2D array is:");
    // for (int i = 0; i < rows1; i++) {
    //     for (int j = 0; j < columns1; j++) {
    //         System.out.print(array1[i][j] + " ");
    //     }
    //     System.out.println();
    // }



// -------------------------------------------------------------------------------------

// Create a 2D array of characters and allow the user to input a word or phrase. 
// Store each character of the input in a separate element of the array. 
// Print out the 2D array after it is filled.

// System.out.print("Enter a word or phrase: ");
// String inputString = sc.nextLine();

// char[][] array1 = new char [1][inputString.length()];

// for (int i = 0; i < inputString.length(); i++) {
//     array1[0][i] = inputString.charAt(i);
// }
// sc.close();

// System.out.println("The 2D array is: ");
// for (int i = 0; i < 1; i++) {
//     for (int j = 0; j < inputString.length(); j++) {
//         System.out.print(array1[i][j] + " ");
//     }
//     System.out.println();
// }


// -------------------------------------------------------------------------------------
// Create a 2D array of doubles and allow the user to input the number of rows and columns.
// Then, fill the array with random numbers generated by the user.

// Random random = new Random();

// System.out.print("Enter the number of rows: ");
// int rows = sc.nextInt();

// System.out.print("Enter the number of columns: ");
// int columns = sc.nextInt();

// double[][] array = new double[rows][columns];

// System.out.println("The 2D array is:");
// for (int i = 0; i < rows; i++) {
//     for (int j = 0; j < columns; j++) {
//         array[i][j] = random.nextDouble();
//         System.out.print(array[i][j] + " ");
//     }
//     System.out.println();
// }
// sc.close();

// -------------------------------------------------------------------------------------

// Create a 2D array of integers and allow the user to input the dimensions of the array. 
// Then, fill the array with random numbers generated by the user and find 
// the second largest number in the array.


// Random random = new Random();

// System.out.print("Enter the number of rows: ");
// int rows = sc.nextInt();

// System.out.print("Enter the number of columns: ");
// int columns = sc.nextInt();

// int[][] array = new int[rows][columns];

// for (int i = 0; i < rows; i++) {
//     for (int j = 0; j < columns; j++) {
//         array[i][j] = random.nextInt();
//     }
// }

// int max = Integer.MIN_VALUE;
// int secondMax = Integer.MIN_VALUE;
// for (int i = 0; i < rows; i++) {
//     for (int j = 0; j < columns; j++) {
//         if (array[i][j] > max) {
//             secondMax = max;
//             max = array[i][j];
//         } else if (array[i][j] > secondMax) {
//             secondMax = array[i][j];
//         }
//     }
// }

// System.out.println("The second largest number in the array is: " + secondMax);


// -------------------------------------------------------------------------------------
// Create a 2D array of characters and allow the user to input a word or phrase. 
// Store each character of the input in a separate element of the array.
//  Print out the 2D array after it is filled and the number of occurrences 
//  of a specific character in the input.

// System.out.print("Enter a word or phrase: ");
// String input = sc.nextLine();
// char[][] array = new char[input.length()][1];
// int count=0;
// for (int i = 0; i < input.length(); i++) {
//     array[i][0] = input.charAt(i);
// }
// System.out.println("Enter a character to find the occurrences:");
// char search = sc.next().charAt(0);
// for (int i = 0; i < input.length(); i++) {
//     if (array[i][0] == search) {
//         count++;
//     }
// }
// for (int i = 0; i < input.length(); i++) {
//     for (int j = 0; j < 1; j++) {
//         System.out.print(array[i][j] + " ");
//     }
// }
// System.out.println("\nThe character "+search+" appears in the input "+count+" times.");

// -------------------------------------------------------------------------------------

// Create a 2D array of Strings and allow the user to input the number of rows and columns. 
// Then, prompt the user to input a word or phrase for each element in the array. 
// Print out the 2D array after it is filled and the number of palindrome 
// words or phrases in the input.

// System.out.print("Enter the number of rows: ");
// int rows = sc.nextInt();
// System.out.print("Enter the number of columns: ");
// int columns = sc.nextInt();
// String[][] array = new String[rows][columns];
// int count=0;
// for (int i = 0; i < rows; i++) {
//     for (int j = 0; j < columns; j++) {
//         System.out.print("Enter a word or phrase for element [" + i + "][" + j + "]: ");
//         array[i][j] = sc.next();
//     }
// }
// for (int i = 0; i < rows; i++) {
//     for (int j = 0; j < columns; j++) {
//         String str = array[i][j];
//         String reverse = new StringBuilder(str).reverse().toString();
//         if (str.equalsIgnoreCase(reverse)) {
//             count++;
//         }
//     }
// }
// for (int i = 0; i < rows; i++) {
//     for (int j = 0; j < columns; j++) {
//         System.out.print(array[i][j] + " ");
//     }
//     System.out.println();
// }
// System.out.println("\nThe number of palindrome words or phrases in the input is: "+count);


// -------------------------------------------------------------------------------------
// Here is some sample Java code that creates a 2D array of doubles, 
// allows the user to input the number of rows and columns, fills the array with
// random numbers generated by the user, and finds the average of all elements in the array:

System.out.print("Enter the number of rows: ");
int rows = sc.nextInt();
System.out.print("Enter the number of columns: ");
int columns = sc.nextInt();
double[][] array = new double[rows][columns];
Random random = new Random();
double sum = 0;
for (int i = 0; i < rows; i++) {
    for (int j = 0; j < columns; j++) {
        array[i][j] = random.nextDouble();
        sum += array[i][j];
    }
}
double average = sum / (rows * columns);
System.out.println("The 2D array is: ");
for (int i = 0; i < rows; i++) {
    for (int j = 0; j < columns; j++) {
        System.out.print(array[i][j] + " ");
    }
    System.out.println();
}
System.out.println("\nThe average of all elements in the array is: " + average);





    }
}
